# -*- coding: utf-8 -*-

# Form implementation generated from reading ui1 file 'MainWindow.ui1'
#
# Created: Tue Jan  6 00:41:25 2015
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from Copy.Ui import CustomWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(660, 552)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridMainLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridMainLayout.setContentsMargins(-1, -1, -1, 9)
        self.gridMainLayout.setObjectName(_fromUtf8("gridMainLayout"))
        self.lineDivider = QtGui.QFrame(self.centralwidget)
        self.lineDivider.setFrameShape(QtGui.QFrame.HLine)
        self.lineDivider.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineDivider.setObjectName(_fromUtf8("lineDivider"))
        self.gridMainLayout.addWidget(self.lineDivider, 1, 0, 1, 1)
        self.tblFiles = CustomWidgets.DNDTableWidget(self.centralwidget)
        self.tblFiles.setAcceptDrops(True)
        self.tblFiles.setObjectName(_fromUtf8("tblFiles"))
        self.tblFiles.setColumnCount(4)
        self.tblFiles.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblFiles.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblFiles.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblFiles.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblFiles.setHorizontalHeaderItem(3, item)
        self.gridMainLayout.addWidget(self.tblFiles, 2, 0, 1, 1)
        self.frmContainer = QtGui.QFrame(self.centralwidget)
        self.frmContainer.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmContainer.setFrameShadow(QtGui.QFrame.Plain)
        self.frmContainer.setObjectName(_fromUtf8("frmContainer"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frmContainer)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.grpDestBox = QtGui.QGroupBox(self.frmContainer)
        self.grpDestBox.setFlat(True)
        self.grpDestBox.setCheckable(False)
        self.grpDestBox.setObjectName(_fromUtf8("grpDestBox"))
        self.gridDestBoxLayout = QtGui.QGridLayout(self.grpDestBox)
        self.gridDestBoxLayout.setObjectName(_fromUtf8("gridDestBoxLayout"))
        self.txtCopyToDir = QtGui.QLineEdit(self.grpDestBox)
        self.txtCopyToDir.setDragEnabled(True)
        self.txtCopyToDir.setObjectName(_fromUtf8("txtCopyToDir"))
        self.gridDestBoxLayout.addWidget(self.txtCopyToDir, 0, 1, 1, 1)
        self.btnCopyToDir = QtGui.QPushButton(self.grpDestBox)
        self.btnCopyToDir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCopyToDir.setObjectName(_fromUtf8("btnCopyToDir"))
        self.gridDestBoxLayout.addWidget(self.btnCopyToDir, 0, 2, 1, 1)
        self.lblCopyTo = QtGui.QLabel(self.grpDestBox)
        self.lblCopyTo.setObjectName(_fromUtf8("lblCopyTo"))
        self.gridDestBoxLayout.addWidget(self.lblCopyTo, 0, 0, 1, 1)
        self.bxDirLevel = QtGui.QSpinBox(self.grpDestBox)
        self.bxDirLevel.setObjectName(_fromUtf8("bxDirLevel"))
        self.gridDestBoxLayout.addWidget(self.bxDirLevel, 1, 1, 1, 1)
        self.lblDirLevel = QtGui.QLabel(self.grpDestBox)
        self.lblDirLevel.setObjectName(_fromUtf8("lblDirLevel"))
        self.gridDestBoxLayout.addWidget(self.lblDirLevel, 1, 0, 1, 1)
        self.targetStatus = QtGui.QProgressBar(self.grpDestBox)
        self.targetStatus.setProperty("value", 0)
        self.targetStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.targetStatus.setObjectName(_fromUtf8("targetStatus"))
        self.gridDestBoxLayout.addWidget(self.targetStatus, 2, 1, 1, 2)
        self.horizontalLayout.addWidget(self.grpDestBox)
        self.line = QtGui.QFrame(self.frmContainer)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.frmPlayer = QtGui.QFrame(self.frmContainer)
        self.frmPlayer.setStyleSheet(_fromUtf8(""))
        self.frmPlayer.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmPlayer.setFrameShadow(QtGui.QFrame.Plain)
        self.frmPlayer.setObjectName(_fromUtf8("frmPlayer"))
        self.vertPlayerLayout = QtGui.QVBoxLayout(self.frmPlayer)
        self.vertPlayerLayout.setMargin(0)
        self.vertPlayerLayout.setObjectName(_fromUtf8("vertPlayerLayout"))
        self.dialVolume = QtGui.QDial(self.frmPlayer)
        self.dialVolume.setObjectName(_fromUtf8("dialVolume"))
        self.vertPlayerLayout.addWidget(self.dialVolume)
        self.frmSeeker = QtGui.QFrame(self.frmPlayer)
        self.frmSeeker.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmSeeker.setFrameShadow(QtGui.QFrame.Raised)
        self.frmSeeker.setObjectName(_fromUtf8("frmSeeker"))
        self.horzSeekerLayout = QtGui.QHBoxLayout(self.frmSeeker)
        self.horzSeekerLayout.setContentsMargins(0, -1, 3, -1)
        self.horzSeekerLayout.setObjectName(_fromUtf8("horzSeekerLayout"))
        self.btnPlay = QtGui.QPushButton(self.frmSeeker)
        self.btnPlay.setIconSize(QtCore.QSize(24, 24))
        self.btnPlay.setAutoDefault(False)
        self.btnPlay.setDefault(False)
        self.btnPlay.setFlat(False)
        self.btnPlay.setObjectName(_fromUtf8("btnPlay"))
        self.horzSeekerLayout.addWidget(self.btnPlay)
        self.seekPlayer = phonon.Phonon.SeekSlider(self.frmSeeker)
        self.seekPlayer.setObjectName(_fromUtf8("seekPlayer"))
        self.horzSeekerLayout.addWidget(self.seekPlayer)
        self.vertPlayerLayout.addWidget(self.frmSeeker)
        self.horizontalLayout.addWidget(self.frmPlayer)
        self.gridMainLayout.addWidget(self.frmContainer, 0, 0, 1, 1)
        self.frmCommand = QtGui.QFrame(self.centralwidget)
        self.frmCommand.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmCommand.setFrameShadow(QtGui.QFrame.Plain)
        self.frmCommand.setObjectName(_fromUtf8("frmCommand"))
        self.horzCommandLayout = QtGui.QHBoxLayout(self.frmCommand)
        self.horzCommandLayout.setContentsMargins(0, 9, 0, 0)
        self.horzCommandLayout.setObjectName(_fromUtf8("horzCommandLayout"))
        self.btnUndoCopy = QtGui.QPushButton(self.frmCommand)
        self.btnUndoCopy.setEnabled(False)
        self.btnUndoCopy.setObjectName(_fromUtf8("btnUndoCopy"))
        self.horzCommandLayout.addWidget(self.btnUndoCopy)
        self.btnPauseCopy = QtGui.QPushButton(self.frmCommand)
        self.btnPauseCopy.setObjectName(_fromUtf8("btnPauseCopy"))
        self.horzCommandLayout.addWidget(self.btnPauseCopy)
        self.btnStartCopy = QtGui.QPushButton(self.frmCommand)
        self.btnStartCopy.setObjectName(_fromUtf8("btnStartCopy"))
        self.horzCommandLayout.addWidget(self.btnStartCopy)
        self.gridMainLayout.addWidget(self.frmCommand, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.tblFiles.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Source", None))
        item = self.tblFiles.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.tblFiles.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tblFiles.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Destination", None))
        self.grpDestBox.setTitle(_translate("MainWindow", "Destination", None))
        self.txtCopyToDir.setPlaceholderText(_translate("MainWindow", "Copy to directory", None))
        self.btnCopyToDir.setText(_translate("MainWindow", "...", None))
        self.lblCopyTo.setText(_translate("MainWindow", "Copy To", None))
        self.lblDirLevel.setText(_translate("MainWindow", "Preserv Level", None))
        self.btnPlay.setText(_translate("MainWindow", "Play", None))
        self.btnUndoCopy.setText(_translate("MainWindow", "Undo", None))
        self.btnPauseCopy.setText(_translate("MainWindow", "Pause Copy", None))
        self.btnStartCopy.setText(_translate("MainWindow", "Start Copy", None))

from PyQt4 import phonon
